version: '3.8'

services:

  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
#    volumes:
#      - 'jenkins_volume:/var/jenkins_home'
    ports:
      - '13000:8080'
      - '5000:5000'
    networks:
      - localcicd
#    restart: always

  docker-proxy:
    image: 'shipyard/docker-proxy' 
    container_name: docker-proxy
    ports:
      - '13001:2375'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - localcicd
#    restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    hostname: 'gitlab.aeontree.com'
    #    environment:
    #      GITLAB_OMNIBUS_CONFIG: |
    #        external_url 'http://gitlab.aeontree.com'
    ports:
      - '13002:80'
    volumes:
      - $HOME/dev/docker-volumes/gitlab/config:/etc/gitlab
      - $HOME/dev/docker-volumes/gitlab/data:/var/opt/gitlab
      - $HOME/dev/docker-volumes/gitlab/logs:/var/log/gitlab
    networks:
      - localcicd
#    restart: always

  vault:
    image: 'vault'
    container_name: vault
    ports:
      - '13009:8200'
    cap_add:
      - 'IPC_LOCK'
    networks:
      - localcicd
#    volumes:


  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloack
    ports:
      - '13003:8080'
    environment:
      - KEYCLOAK_USER=admin       # TODO use env var. or vault
      - KEYCLOAK_PASSWORD=admin   # TODO use env var. or vault
    networks:
      - localcicd
#    restart: always

  sonarqube:
    image: 'sonarqube'
    container_name: sonarqube
    ports:
      - '13004:9000'
    volumes:
      - 'sonarqube-volume:/opt/sonarqube' # TODO change named volume to host volume
    networks:
      - localcicd
#    restart: always

  artifactory:
    image: 'docker.bintray.io/jfrog/artifactory-oss:latest'
    container_name: artifactory
    ports:
      - '13005:8081'
      - '13006:8082'
    volumes:
      - 'artifactory-volume:/var/opt/jfrog/artifactory' # TODO change named volume to host volume. get article from work laptop
    networks:
      - localcicd
#    restart: always

  nexus:
    image: 'sonatype/nexus3'
    container_name: nexus
    ports:
      - '13007:8081'
    volumes:
      - 'nexus-volume:/nexus-data' # TODO change named volume to host volume. get article from work laptop
    networks:
      - localcicd
##    restart: always

  portainer:
    image: 'portainer/portainer-ce'
    container_name: portainer
    ports:
#      - '8000:8000' # used by EDGE agent
      - '13008:9000'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - 'portainer-data:/data' # TODO change named volume to host volume. get article from work laptop


volumes:
  artifactory-volume:
#  jenkins-volume:
  nexus-volume:
  portainer-data:
  sonarqube-volume:

networks:
  localcicd:

# kafka
# add ctop https://github.com/bcicen/ctop
# add dive https://github.com/wagoodman/dive
# ldd, strings, upx
# postgresql
# cassandra
# elastic services

# TODO watch oracle twitch recording