version: '3.8'

services:

  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    ports:
      - '13000:8080'
    volumes:
      - 'jenkins-volume:/var/jenkins_home'
    networks:
      - localcicd
    restart: always

  docker-proxy:
    image: 'shipyard/docker-proxy'
    container_name: docker-proxy
    ports:
      - '13001:2375'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    ports:
      - '13002:80'
    hostname: 'gitlab.aeontree.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.aeontree.com'
    restart: always

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloack
    ports:
      - '13003:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: always

  sonarqube:
    image: 'sonarqube'
    container_name: sonarqube
    ports:
      - '13004:9000'
    volumes:
      - 'sonarqube-volume:/opt/sonarqube'
    networks:
      - localcicd
    restart: always

  artifactory:
    image: 'docker.bintray.io/jfrog/artifactory-oss:latest'
    container_name: artifactory
    ports:
      - '13005:8081'
      - '13006:8082'
    volumes:
      - 'artifactory-volume:/var/opt/jfrog/artifactory'
    restart: always

  nexus:
    image: 'sonatype/nexus3'
    container_name: nexus
    ports:
      - '13007:8081'
    volumes:
      - 'nexus-volume:/nexus-data'
    networks:
      - localcicd
    restart: always

volumes:
  artifactory-volume:
  jenkins-volume:
  nexus-volume:
  sonarqube-volume:

networks:
  localcicd: